name: slack-notification

on: 
  pull_request: 
    branches: [ master ]

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"C01TUGRFZPA\",\"text\":\"Pull request iniciado\"}'
